[package]
name = "alamem"
version = "0.1.2"
edition = "2021"

[dependencies]
indicatif = "0.18"
rustc-hash = "2.1"
rayon = "1.7"
needletail = { version = "0.7", default-features = false, features = ["flate2"] }
flate2 = { version = "1.0", features = ["zlib-rs"] }
mimalloc = "0.1"
clap = { version = "4.6", features= ["derive"]}
libc = "0.2"
crossbeam = "0.8"
memchr = "2.7"

[dev-dependencies]
assert_cmd = "2.0"
tempfile = "3.10"

[profile.release]
opt-level = 3            # Maximizes aggressive speed optimizations (Default: 3)
lto = "fat"              # Enables global, cross-crate Link-Time Optimization
codegen-units = 1        # Forces single-threaded backend compilation for best inlining
debug = false

[profile.dist]
inherits = "release"
panic = "abort"

[profile.profiling]
inherits = "release"
debug = 1
strip = false

[[example]]
name = "ani_simulator"
path = "examples/ani_simulator.rs"
